name: issueopened

on:
  issues:
    types: opened

  workflow_dispatch:

jobs:

  welcome:
    runs-on: ubuntu-latest
    steps:
    - name: Get Issue Number
      run: curl -O https://api.github.com/repos/nthnchu/nathanchu.com/issues

    - name: Install nodejs and npm
      uses: actions/setup-node@v1
      with:
        node-version: '12.18.3'

    - name: Decode json and post comment
      run: |
        ISSUE=`node -e "require('fs').readFile('issues', (err, data) => { if (err) throw err; data = JSON.parse(data)[0]['number']; console.log(data); })"`
        curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.BOT_GH_TOKEN }}" https://api.github.com/repos/nthnchu/nathanchu.com/issues/$ISSUE/comments \
        -d '{"body":"Hey there :wave:! Thank you for reporting an issue. Make sure this issue has a clear title and description, including how to reproduce it if it\'s a bug. You also should follow the issue template and answer the questions inside the description. You should expect a response within the next day!\n\n_This message was generated automatically by a bot._"}'
        curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.BOT_GH_TOKEN }}" https://api.github.com/repos/nthnchu/nathanchu.com/issues/$ISSUE/labels -d '{"labels":["triage"]}'
