# This is a basic workflow to help you get started with Actions

name: issueopened

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues:
    types: opened
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - run: curl -O https://api.github.com/repos/nthnchu/nathanchu.com/issues
    - uses: actions/setup-node@v1
      with:
        node-version: '12.18.3'
    - name: Run a one-line script
      run: |
        ISSUE=`node -e "require('fs').readFile('issues', (err, data) => { if (err) throw err; data = JSON.parse(data)[0]['number']; console.log(data); })"`
        curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.BOT_GH_TOKEN }}" https://api.github.com/repos/nthnchu/nathanchu.com/issues/$ISSUE/comments -d '{"body":"Hey there :wave:! Thank you for reporting an issue. Make sure this issue has a clear title and description, so it can be fixed faster. You should expect a response within the next day!\n\n_This message was generated by a bot_"}'
